FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# BN

Webscrapper APIUp

## Jobs Collection [/api/jobs]

### Get All Jobs [GET]

+ Response 200 (application/json)

        [
            {
                "id": "1",
                "frn": 2,
                "status": "ONGOING",
                "percentageComplete": 45,
                "dateTimeStarted": "2018-03-15T15:25:19+00:00",
                "dateTimeCompleted": null
            }, 
            {
                "id": "1",
                "frn": 2,
                "status": "COMPLETED",
                "percentageComplete": 100,
                "dateTimeStarted": "2018-03-15T15:25:19+00:00",
                "dateTimeCompleted": "2018-04-15T15:25:19+00:00"
            }
        ]


### Process a job [POST]

+ Request (application/json)

        
        [
            {
                "frn": 1,
                "maxLevel": 1,
                "url": "https://app.apiary.io/bn4/editor",
                "linksPerLevel":10
            }, 
            {
                "frn": 2,
                "maxLevel": 1,
                "url": "https://app.apiary.io/bn4/editor",
                "linksPerLevel":10
            }
        ]
        

+ Response 201 (application/json)

    + Headers

            Location: /api/jobs

    + Body

            
            [
                {
                    "id": "1",
                    "frn": 2,
                    "status": "ONGOING",
                    "percentageComplete": 45,
                    "dateTimeStarted": "2018-03-15T15:25:19+00:00",
                    "dateTimeCompleted": null
                }, 
                {
                    "id": "1",
                    "frn": 2,
                    "status": "COMPLETED",
                    "percentageComplete": 100,
                    "dateTimeStarted": "2018-03-15T15:25:19+00:00",
                    "dateTimeCompleted": "2018-04-15T15:25:19+00:00"
                }
            ]
            


### Fetch a single Job [GET  /api/jobs/{id}]

+ Parameters
    + id (string) -  Job ID
    
+ Response 200 (application/json)

        {
            "id": "1",
            "frn": 2,
            "status": "ONGOING",
            "percentageComplete": 45,
            "dateTimeStarted": "2018-03-15T15:25:19+00:00",
            "dateTimeCompleted": null
        }
        
        
### Jobs status [GET  /api/jobs/status]

    
    
+ Response 200 (application/json)

        {
            "percentCompleted": "27.48",
            "totalCanceled": 0,
            "totalCompleted": 1,
            "totalJobs": 4,
            "totalOngoing": 1
        }