FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# BN

## Jobs Collection [/api/jobs]

### Get All Jobs [GET]

+ Response 200 (application/json)

        [
            {
                "jobs": [
                    {
                        "id": "1",
                        "frn": 2,
                        "status": "ONGOING",
                        "percentage_complete": 45,
                        "job_stated": "2018-03-15T15:25:19+00:00",
                        "job_ended": null
                    }, {
                        "id": "1",
                        "frn": 2,
                        "status": "COMPLETED",
                        "percentage_complete": 100,
                        "job_stated": "2018-03-15T15:25:19+00:00",
                        "job_ended": "2018-04-15T15:25:19+00:00"
                    }
                ]
            }
        ]


### Process a job [POST]

+ Request (application/json)

        {
            "companies": [
                    {
                        "frn": 1,
                        "maxLevel": 1,
                        "url": "https://app.apiary.io/bn4/editor",
                        "linksPerLevel":10
                    }, {
                        "frn": 2,
                        "maxLevel": 1,
                        "url": "https://app.apiary.io/bn4/editor",
                        "linksPerLevel":10
                    }
                ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /api/jobs

    + Body

            {
            "job_ids": [
                    {
                        "id": 1,
                        "status": "STARTED"
                    }, {
                        "id": 2,
                        "status": "STARTED"
                    }
                ]
            }


### Fetch a single Job [GET  /api/jobs/{id}]

+ Parameters
    + id (string) -  Job ID
    
+ Response 200 (application/json)

        {
            "id": "1",
            "frn": 2,
            "status": "ONGOING",
            "percentage_complete": 45,
            "job_stated": "2018-03-15T15:25:19+00:00",
            "job_ended": null
        }